/**
 * @author Fabian Conde Lafuente
 * @file vec2_double.h
 * @brief Double-precision 2D vector math library.
 *
 * This header defines the rtm_dvec2 type and its associated operations,
 * including constructors, getters/setters, and mathematical functions.
 * All functions are implemented as inline or static inline depending on
 * the RTM_USE_STATIC_INLINE configuration.
 * 
 * The comments of this file has been generated by ChatGPT, so it may 
 * contain some errors.
 */
#ifndef RTM_VEC2_DOUBLE_H
#define RTM_VEC2_DOUBLE_H
// double vector 2 header file

#ifdef __cplusplus
extern "C" {
#endif

#include "../detail/vec2_types.h"
#include "../detail/vec_define.h"

/*===========================================================
 *  DECLARATIONS
 *===========================================================*/

/**
 * @brief Returns a 2D zero vector (0.0, 0.0).
 */
RTMDEF rtm_dvec2 rtm_dvec2_zero(void);

/**
 * @brief Returns a 2D vector of ones (1.0, 1.0).
 */
RTMDEF rtm_dvec2 rtm_dvec2_one(void);

/**
 * @brief Constructs a 2D vector with the given components.
 * @param x The x component.
 * @param y The y component.
 * @return The constructed vector.
 */
RTMDEF rtm_dvec2 rtm_dvec2_construct(double x, double y);

/**
 * @brief Constructs a 2D vector with both components set to the same value.
 * @param v The uniform value for both components.
 * @return The constructed vector.
 */
RTMDEF rtm_dvec2 rtm_dvec2_construct_uniform(double v);

/**
 * @brief Copies a vector into another.
 * @param out Destination vector.
 * @param src Source vector.
 */
RTMDEF void rtm_dvec2_copy(rtm_dvec2* out, const rtm_dvec2* src);

/**
 * @brief Returns a copy of the given vector.
 * @param src Source vector.
 * @return The cloned vector.
 */
RTMDEF rtm_dvec2 rtm_dvec2_clone(const rtm_dvec2* src);

/**
 * @brief Returns the x component of a vector.
 * @param v The input vector.
 * @return The x component.
 */
RTMDEF double rtm_dvec2_get_x(const rtm_dvec2* v);

/**
 * @brief Returns the y component of a vector.
 * @param v The input vector.
 * @return The y component.
 */
RTMDEF double rtm_dvec2_get_y(const rtm_dvec2* v);

/**
 * @brief Sets the x component of a vector.
 * @param v Pointer to the vector.
 * @param x The new x value.
 */
RTMDEF void rtm_dvec2_set_x(rtm_dvec2* v, double x);

/**
 * @brief Sets the y component of a vector.
 * @param v Pointer to the vector.
 * @param y The new y value.
 */
RTMDEF void rtm_dvec2_set_y(rtm_dvec2* v, double y);

/**
 * @brief Adds two 2D vectors.
 * @param a First operand.
 * @param b Second operand.
 * @return Result of (a + b).
 */
RTMDEF rtm_dvec2 rtm_dvec2_add(const rtm_dvec2* a, const rtm_dvec2* b);

/**
 * @brief Adds two 2D vectors and stores the result in an output vector.
 * @param out Destination vector.
 * @param a First operand.
 * @param b Second operand.
 */
RTMDEF void rtm_dvec2_add_ex(rtm_dvec2* out, const rtm_dvec2* a, const rtm_dvec2* b);

/**
 * @brief Subtracts one 2D vector from another.
 * @param a First operand.
 * @param b Second operand.
 * @return Result of (a - b).
 */
RTMDEF rtm_dvec2 rtm_dvec2_sub(const rtm_dvec2* a, const rtm_dvec2* b);

/**
 * @brief Subtracts one vector from another and stores the result.
 * @param out Destination vector.
 * @param a First operand.
 * @param b Second operand.
 */
RTMDEF void rtm_dvec2_sub_ex(rtm_dvec2* out, const rtm_dvec2* a, const rtm_dvec2* b);

/**
 * @brief Multiplies a vector by a scalar.
 * @param v Input vector.
 * @param s Scalar multiplier.
 * @return The scaled vector.
 */
RTMDEF rtm_dvec2 rtm_dvec2_mult(const rtm_dvec2* v, double s);

/**
 * @brief Multiplies a vector by a scalar and stores the result.
 * @param out Destination vector.
 * @param v Input vector.
 * @param s Scalar multiplier.
 */
RTMDEF void rtm_dvec2_mult_ex(rtm_dvec2* out, const rtm_dvec2* v, double s);

/**
 * @brief Divides a vector by a scalar.
 * @param v Input vector.
 * @param s Scalar divisor.
 * @return The scaled vector.
 */
RTMDEF rtm_dvec2 rtm_dvec2_div(const rtm_dvec2* v, double s);

/**
 * @brief Divides a vector by a scalar and stores the result.
 * @param out Destination vector.
 * @param v Input vector.
 * @param s Scalar divisor.
 */
RTMDEF void rtm_dvec2_div_ex(rtm_dvec2* out, const rtm_dvec2* v, double s);

/**
 * @brief Computes the squared length (magnitude²) of a vector.
 * @param v Input vector.
 * @return The squared length.
 */
RTMDEF double rtm_dvec2_length_squared(const rtm_dvec2* v);

/**
 * @brief Computes the Euclidean length (magnitude) of a vector.
 * @param v Input vector.
 * @return The length.
 */
RTMDEF double rtm_dvec2_length(const rtm_dvec2* v);

/**
 * @brief Normalizes a vector in place to unit length.
 * @param v The vector to normalize.
 */
RTMDEF void rtm_dvec2_normalize(rtm_dvec2* v);

/**
 * @brief Normalizes a vector and stores the result in another vector.
 * @param out Destination vector.
 * @param v Input vector.
 */
RTMDEF void rtm_dvec2_normalize_ex(rtm_dvec2* out, const rtm_dvec2* v);

/**
 * @brief Computes the dot product of two vectors.
 * @param a First operand.
 * @param b Second operand.
 * @return The scalar dot product value.
 */
RTMDEF double rtm_dvec2_dot(const rtm_dvec2* a, const rtm_dvec2* b);

/**
 * @brief Computes the Euclidean distance between two vectors.
 * @param a First vector.
 * @param b Second vector.
 * @return The distance between the two vectors.
 */
RTMDEF double rtm_dvec2_distance(const rtm_dvec2* a, const rtm_dvec2* b);

/**
 * @brief Returns the negated vector (-x, -y).
 * @param v Input vector.
 * @return Negated vector.
 */
RTMDEF rtm_dvec2 rtm_dvec2_neg(const rtm_dvec2* v);

/**
 * @brief Negates a vector and stores the result.
 * @param out Destination vector.
 * @param v Input vector.
 */
RTMDEF void rtm_dvec2_neg_ex(rtm_dvec2* out, const rtm_dvec2* v);

/**
 * @brief Performs element-wise (Hadamard) multiplication of two vectors.
 * @param a First operand.
 * @param b Second operand.
 * @return Component-wise product of a and b.
 */
RTMDEF rtm_dvec2 rtm_dvec2_hadamard(const rtm_dvec2* a, const rtm_dvec2* b);

RTMDEF rtm_dvec2 rtm_dvec2_clamp(rtm_dvec2* v, double min, double max);
RTMDEF rtm_dvec2 rtm_dvec2_lerp(const rtm_dvec2* a, const rtm_dvec2* b, double t);

RTMDEF double rtm_dvec2_min_value(const rtm_dvec2* v);
RTMDEF double rtm_dvec2_max_value(const rtm_dvec2* v);

RTMDEF rtm_dvec2 rtm_dvec2_min(const rtm_dvec2* a, const rtm_dvec2* b);
RTMDEF rtm_dvec2 rtm_dvec2_max(const rtm_dvec2* a, const rtm_dvec2* b);

RTMDEF RTM_bool rtm_dvec2_equal(const rtm_dvec2* a, const rtm_dvec2* b);
RTMDEF RTM_bool rtm_dvec2_aprox(const rtm_dvec2* a, const rtm_dvec2* b, double eps);
RTMDEF RTM_bool rtm_dvec2_greater(const rtm_dvec2* a, const rtm_dvec2* b);
RTMDEF RTM_bool rtm_dvec2_ge(const rtm_dvec2* a, const rtm_dvec2* b);
RTMDEF RTM_bool rtm_dvec2_less(const rtm_dvec2* a, const rtm_dvec2* b, double eps);
RTMDEF RTM_bool rtm_dvec2_le(const rtm_dvec2* a, const rtm_dvec2* b, double eps);

RTMDEF rtm_dvec2 rtm_dvec2_perp(const rtm_dvec2* v);
RTMDEF rtm_dvec2 rtm_dvec2_rotate(const rtm_dvec2* v, double angle);

/*===========================================================
 *  IMPLEMENTATION
 *===========================================================*/
#ifdef RTM_IMPLEMENTATION

#include <math.h>


/*===========================================================
 *  rtm_dvec2 Constructors
 *===========================================================*/
RTMDEF rtm_dvec2 rtm_dvec2_zero(void) { return VEC2_LITERAL(0.0, 0.0); }
RTMDEF rtm_dvec2 rtm_dvec2_one(void) {return VEC2_LITERAL(1.0,1.0);}
RTMDEF rtm_dvec2 rtm_dvec2_construct(double x, double y) { return VEC2_LITERAL(x, y); }
RTMDEF rtm_dvec2 rtm_dvec2_construct_uniform(double v) { return VEC2_LITERAL(v, v); }

/*
 *  COPY
 */
RTMDEF void rtm_dvec2_copy(rtm_dvec2* out, const rtm_dvec2* src)
{
    out->x = src->x;
    out->y = src->y;
}

RTMDEF rtm_dvec2 rtm_dvec2_clone(const rtm_dvec2* src) { return *src; }

/*===========================================================
 *  rtm_dvec2 Getters / Setters
 *===========================================================*/
RTMDEF double rtm_dvec2_get_x(const rtm_dvec2* v) { return v->x; }
RTMDEF double rtm_dvec2_get_y(const rtm_dvec2* v) { return v->y; }
RTMDEF void   rtm_dvec2_set_x(rtm_dvec2* v, double x) { v->x = x; }
RTMDEF void   rtm_dvec2_set_y(rtm_dvec2* v, double y) { v->y = y; }

/*===========================================================
 *  rtm_dvec2 Math
 *===========================================================*/
RTMDEF rtm_dvec2 rtm_dvec2_add(const rtm_dvec2* a, const rtm_dvec2* b)
{
    return VEC2_LITERAL(a->x + b->x, a->y + b->y);
}

RTMDEF void rtm_dvec2_add_ex(rtm_dvec2* out, const rtm_dvec2* a, const rtm_dvec2* b)
{
    out->x = a->x + b->x; out->y = a->y + b->y;
}

RTMDEF rtm_dvec2 rtm_dvec2_sub(const rtm_dvec2* a, const rtm_dvec2* b)
{
    return VEC2_LITERAL(a->x - b->x, a->y - b->y);
}

RTMDEF void rtm_dvec2_sub_ex(rtm_dvec2* out, const rtm_dvec2* a, const rtm_dvec2* b)
{
    out->x = a->x - b->x; out->y = a->y - b->y;
}

RTMDEF rtm_dvec2 rtm_dvec2_mult(const rtm_dvec2* v, double s)
{
    return VEC2_LITERAL(v->x * s, v->y * s);
}

RTMDEF void rtm_dvec2_mult_ex(rtm_dvec2* out, const rtm_dvec2* v, double s)
{
    out->x = v->x * s; out->y = v->y * s;
}

RTMDEF rtm_dvec2 rtm_dvec2_div(const rtm_dvec2* v, double s)
{
    return VEC2_LITERAL(v->x / s, v->y / s);
}

RTMDEF void rtm_dvec2_div_ex(rtm_dvec2* out, const rtm_dvec2* v, double s)
{
    out->x = v->x / s; out->y = v->y / s;
}

RTMDEF double rtm_dvec2_length_squared(const rtm_dvec2* v)
{
    return v->x * v->x + v->y * v->y;
}

RTMDEF double rtm_dvec2_length(const rtm_dvec2* v)
{
    return sqrt(rtm_dvec2_length_squared(v));
}

RTMDEF void rtm_dvec2_normalize(rtm_dvec2* v)
{
    double l = rtm_dvec2_length(v); v->x /= l; v->y /= l;
}

RTMDEF void rtm_dvec2_normalize_ex(rtm_dvec2* out, const rtm_dvec2* v)
{
    double l = rtm_dvec2_length(v); out->x = v->x / l; out->y = v->y / l;
}

RTMDEF double rtm_dvec2_dot(const rtm_dvec2* a, const rtm_dvec2* b)
{
    return a->x * b->x + a->y * b->y;
}

RTMDEF double rtm_dvec2_distance(const rtm_dvec2* a, const rtm_dvec2* b)
{
    double dx = a->x - b->x, dy = a->y - b->y;
    return sqrt(dx * dx + dy * dy);
}

RTMDEF rtm_dvec2 rtm_dvec2_neg(const rtm_dvec2* v)
{
    return VEC2_LITERAL(-v->x, -v->y);
}

RTMDEF void rtm_dvec2_neg_ex(rtm_dvec2* out, const rtm_dvec2* v)
{
    out->x = -v->x; out->y = -v->y;
}

RTMDEF rtm_dvec2 rtm_dvec2_hadamard(const rtm_dvec2* a, const rtm_dvec2* b)
{
    return VEC2_LITERAL(a->x * b->x, a->y * b->y);
}

#endif // !RTM_IMPLEMENTATION

#ifdef __cplusplus
}
#endif

#endif //!RTM_VEC2_DOUBLE_H